[package]
name = "mcl"
version = "0.1.0"
authors = ["72-S"]
edition = "2021"

[dependencies]
clap = "4.5.27"
color-eyre = "0.6.3"
config = "0.15.6"
crossterm = "0.28.1"
dirs-next = "2.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"]}
serde_derive = "1.0.217"
lazy_static = "1.5.0"
colored = "3.0.0"
chrono = "0.4.39"

