[general]
debug = false

[colors]
background = "#1e1e1e"     
foreground = "white"        
border_focused = "white"     
border_unfocused = "darkgray" 
row_highlight = "yellow"     
row_background = "darkgray"  
row_alternate_bg = "#282828"  
